version: '3'
services:
  contacts_app:
    image: contacts_storage
    container_name: contacts_app
    ports:
      - "8100:8080"
    depends_on:
      - contacts_pg
  contacts_pg:
    image: postgres
    container_name: contacts_pg
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contacts
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql