name: Java CI with Maven And multiple java versions

on:
  push:
      branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:   
      matrix:
        java: [ 1.8, 1.11, 1.12, 1.13 ]
    name: Java ${{ matrix.java}} sample
    steps:
     - uses: actions/checkout@v2
     - name: Setup java
       uses: actions/setup-java@v1
       with:
         java-version: ${{ matrix.java }}
     - name: Build with Maven
       run: mvn -B package --file pom.xml
