name: Java CI with Maven And multiple java versions

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:   
      matrix:
        java: [ 8, 11.03, 12, 13 ]
    name: Java ${{ matrix.java}} sample
    steps:
     - uses: actions/checkout@v2
     - name: Setup java
       uses: actions/setup-java@v1
       with:
         java-version: ${{ matrix.java }}
     - name: Build with Maven
       run: mvn -B package --file pom.xml
